spring.application.name=tenda-online

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbuy
spring.datasource.username=smartbuy
spring.datasource.password=smartbuy
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true

# Inicializar datos
spring.sql.init.mode=always

# Servidor
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info